.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. supcoin_qt test_supcoin_qt
clean: FORCE
	$(MAKE) -C .. supcoin_qt_clean test_supcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_supcoin_qt_check
supcoin-qt supcoin-qt.exe: FORCE
	 $(MAKE) -C .. supcoin_qt
